module.exports.allowedSubjects = {
  maths: {
    maths: ["Primary", "KS3", "IB", "GCSE", "iGCSE", "A-Level", "Degree"],
    statistics: ["A-Level", "Degree"],
    "pure maths": ["A-Level", "Degree"],
    "further maths": ["IB", "A-Level", "Degree"],
    mechanics: ["A-Level", "Degree"],
  },
  english: {
    english: ["Primary", "KS3", "IB", "GCSE", "iGCSE", "A-Level", "Degree"],
    "English literature": [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "iGCSE",
      "A-Level",
      "Degree",
    ],
    Phonics: ["Primary", "KS3"],
    Reading: ["Primary", "KS3"],
    "Spelling, Punctuation and Grammar": ["Primary", "KS3"],
  },
  Writing: {
    Writing: [],
    "Essay Writing": [],
    Dissertation: [],
    Writing: [],
    "Essay Writing": [],
    Playwriting: [],
    Journalism: [],
    Stylistics: [],
    "Creative writing": [],
  },
  science: {
    science: ["Primary", "KS3", "IB", "GCSE", "iGCSE", "A-Level"],
    Biology: ["IB", "GCSE", "iGCSE", "A-Level", "Degree"],
    Physics: ["IB", "GCSE", "iGCSE", "A-Level", "Degree"],
    Astronomy: ["IB", "GCSE", "iGCSE", "A-Level", "Degree"],
    Physiology: ["IB", "GCSE", "iGCSE", "A-Level", "Degree"],
    Biochemistry: ["IB", "GCSE", "iGCSE", "A-Level", "Degree"],
    "Biomedical Science": ["IB", "GCSE", "iGCSE", "A-Level", "Degree"],
    "Environmental Science": ["IB", "GCSE", "iGCSE", "A-Level", "Degree"],
    Geology: ["IB", "GCSE", "A-Level", "Degree"],
  },
  "Primary and Early Years": {
    "Primary and Early Years": ["Key Stage 1", "Key Stage 2"],
    "Early Years and Reception": ["Key Stage 1", "Key Stage 2"],
    Primary: ["Key Stage 1", "Key Stage 2"],
    "Eleven Plus 11+": ["Key Stage 1", "Key Stage 2"],
    SATs: ["Key Stage 1", "Key Stage 2"],
  },
  Languages: {
    languages: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Afrikaans: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Arabic: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Bengali: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Bulgarian: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Cantonese: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Catalan: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Croatian: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Czech: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Danish: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Dutch: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    "English as a Foreign Language EFL": [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    "IELTS and ESOL": [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Estonian: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Farsi: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Finnish: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    French: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Gaelic: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    German: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    "Greek Modern": [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Gujarati: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Hebrew: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Hindi: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Hungarian: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Italian: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Japanese: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Kashmiri: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Korean: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Latin: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Lithuanian: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Malay: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Mandarin: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Norwegian: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Persian: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Polish: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Portuguese: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Punjabi: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Romanian: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Malay: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Russian: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Russian: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Serbian: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    "Sign Language": [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Spanish: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Swedish: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Tamil: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Telugu: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Tamil: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Turkish: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Ukrainian: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Vietnamese: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Welsh: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
    Tamil: [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "A - Level",
      "Beginner",
      "Intermediate",
      "Advanced",
    ],
  },
  Vocational: {
    Agriculture: ["IB", "GCSE", "A-Level", "Degree"],
    Nursing: ["A-Level", "Degree"],
    "Functional Skills": ["Maths", "English", "Level 1", "Level 2"],
    "Social Work": ["A-Level", "Degree"],
    Construction: ["A-Level", "Degree"],
    Engineering: ["IB", "GCSE", "A-Level", "Degree"],
    "General Studies": ["A-Level", "Degree"],
    "Health and Social Care": ["IB", "GCSE", "A-Level", "Degree"],
    Hospitality: ["IB", "GCSE", "A-Level", "Degree"],
    Journalism: ["IB", "GCSE", "A-Level", "Degree"],
    Law: ["IB", "GCSE", "A-Level", "Degree"],
    "Leisure Studies": ["A-Level", "Degree"],
    "Leisure and Tourism": ["IB", "GCSE", "A-Level", "Degree"],
    "Media Studies": ["IB", "GCSE", "A-Level", "Degree"],
    Medicine: ["A-Level", "Degree"],
    Neuroscience: ["A-Level", "Degree"],
    "Travel and Tourism": ["IB", "GCSE", "A-Level", "Degree"],
  },
  "Business and accounting": {
    Accounting: ["IB", "GCSE", "iGCSE", "A-Level", "Degree"],
    "Business Studies": ["IB", "GCSE", "iGCSE", "A-Level", "Degree"],
    Finance: ["A-Level", "Degree"],
    Marketing: ["A-Level", "Degree"],
  },
  "Humanities and Art": {
    Art: ["Primary", "KS3", "IB", "GCSE", "iGCSE", "A-Level", "Degree"],
    Anthropology: ["A-Level", "Degree"],
    Archaeology: ["A-Level", "Degree"],
    Citizenship: ["IB", "GCSE", "iGCSE", "A-Level", "Degree"],
    Classics: ["IB", "GCSE", "iGCSE", "A-Level", "Degree"],
    "Design and Technology": ["IB", "GCSE", "iGCSE", "A-Level", "Degree"],
    Electronics: ["IB", "GCSE", "iGCSE", "A-Level", "Degree"],
    "Food Technology": [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "iGCSE",
      "A-Level",
      "Degree",
    ],
    "Graphic Design": ["KS3", "IB", "GCSE", "iGCSE", "A-Level", "Degree"],
    Manufacturing: ["IB", "GCSE", "iGCSE", "A-Level", "Degree"],
    "Resistant Materials": ["KS3", "IB", "GCSE", "iGCSE", "A-Level", "Degree"],
    "Systems and Control": ["KS3", "IB", "GCSE", "iGCSE", "A-Level", "Degree"],
    Textiles: ["KS3", "IB", "GCSE", "iGCSE", "A-Level", "Degree"],
    Drama: ["Primary", "KS3", "IB", "GCSE", "iGCSE", "A-Level", "Degree"],
    Economics: ["IB", "GCSE", "iGCSE", "A-Level", "Degree"],
    "Film Studies": ["IB", "GCSE", "iGCSE", "A-Level", "Degree"],
    "Gender and Sexuality Studies": [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "iGCSE",
      "A-Level",
      "Degree",
    ],
    Geography: ["Primary", "KS3", "IB", "GCSE", "iGCSE", "A-Level", "Degree"],
    History: ["Primary", "KS3", "IB", "GCSE", "iGCSE", "A-Level", "Degree"],
    "History of Art": ["IB", "GCSE", "iGCSE", "A-Level", "Degree"],
    "Home Economics": ["KS3", "IB", "GCSE", "iGCSE", "A-Level", "Degree"],
    "Child Development": ["KS3", "IB", "GCSE", "iGCSE", "A-Level", "Degree"],
    "Food and Nutrition": ["KS3", "IB", "GCSE", "iGCSE", "A-Level", "Degree"],
    Humanities: ["Primary", "KS3", "IB", "GCSE", "iGCSE", "A-Level", "Degree"],
    "Performing Arts": [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "iGCSE",
      "A-Level",
      "Degree",
    ],
    Philosophy: ["A-Level", "Degree"],
    Photography: ["IB", "GCSE", "iGCSE", "A-Level", "Degree"],
    Psychology: ["IB", "GCSE", "iGCSE", "A-Level", "Degree"],
    "Religious Education": [
      "Primary",
      "KS3",
      "IB",
      "GCSE",
      "iGCSE",
      "A-Level",
      "Degree",
    ],
    Sociology: ["IB", "GCSE", "iGCSE", "A-Level", "Degree"],
    Politics: ["GCSE", "iGCSE", "A-Level", "Degree", "Modern Studies"],
    "Art & Design ": ["GCSE", "iGCSE", "A-Level", "Degree", "Modern Studies"],
  },
  "Professional courses": {
    QTS: [],
    "Maths Skills": [],
    "Numeracy Skills": [],
    "Literacy Skills": [],
    "UCAT and BMAT": [],
    "Personal Statement Help": [],
    "CV Help": [],
  },
  law: {
    law: ["A-level", "Degree"],
    Criminology: ["A-level", "Degree"],
  },
  music: {
    Music: [
      "Primary",
      "KS3",
      "GCSE",
      "iGCSE",
      "AS/A Level",
      "Degree",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    "Music Technology": [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    "Music Theory": [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Composition: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Accordion: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Bagpipes: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Banjo: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    "Bass Guitar": [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Bassoon: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Cello: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Clarinet: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Conducting: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Cornet: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    "Double Bass": [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Drums: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Euphonium: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    "Flugel Horn": [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Flute: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    "French Horn": [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Guitar: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Acoustic: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Electric: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Blues: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Rock: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Harmonica: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Harp: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Harpsichord: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Keyboard: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Mandolin: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Oboe: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Organ: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Percussion: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Piano: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Piccolo: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Recorder: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Saxophone: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Singing: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Sitar: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    "Tenor Horn": [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Trombone: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Trumpet: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Tuba: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Ukulele: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Viola: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
    Violin: [
      "Beginner",
      "Intermediate",
      "Advanced",
      "Grade 1-3",
      "Grade 4-5",
      "Grade 6-7",
      "Grade 8+",
    ],
  },
  "Admissions Primary": {
    "Admissions Primary": [],
    "Seven Plus 7+": [],
    "Eight Plus 8+": [],
    "Non-verbal reasoning": [],
    "Verbal reasoning": [],
    "Common Entrance Admissions": [],
    Classics: [],
    "English Common Entrance": [],
    "Geography Common Entrance": [],
    "History Common Entrance": [],
    "Religious Studies Common Entrance": [],
    "Science Common Entrance": [],
    "Benenden School admissions": [],
    "Charterhouse School admissions": [],
    "City of London School admissions": [],
    "Dulwich College school admissions": [],
    "Eltham College school admissions": [],
    "Emmanuel College Wimbledon school admissions": [],
    "Eton admission": [],
    "Eton College admissions": [],
    "Francis Holland School admission": [],
    "Godolphin & Latymer School admissions": [],
    "Haberdasher's Aske's School admissions": [],
    "Harrow admission": [],
    "Harrow School admissions": [],
    "Henrietta Barnett School admissions": [],
    "Highgate School admissions": [],
    "James Allen's Girls' School admissions JAGS": [],
    "King's College Wimbledon school admissions": [],
    "Lady Eleanor Holles School admissions": [],
    "Latymer School admissions": [],
    "Lycee Francais Charles de Gaulle school admissions": [],
    "Marlborough College school admissions": [],
    "Oundle School admissions": [],
    "Putney High School admissions": [],
    "Queen's Gate school admissions": [],
    "Radley College school admissions": [],
    "Sevenoaks School admissions": [],
    "St Paul's admission": [],
    "St. Mary's Ascot school admissions": [],
    "St. Paul's Girls' School admissions": [],
    "St. Paul's School admissions": [],
    "The Latymer School admissions": [],
    "Tonbridge School admissions": [],
    "Wellington College school admissions": [],
    "Westminster admission": [],
    "Westminster School admissions": [],
    "Winchester admission": [],
    "Winchester College school admissions": [],
    "Wycombe Abbey admissions": [],
    "Wycombe Abbey school admissions": [],
    "Oxbridge Admissions": [],
    "School Advice": [],
    "University Advice": [],
    "Blue Coat School Liverpool admissions": [],
    "Merchant Taylors Schoool admissions": [],
  },
  "Special Educational Needs": {
    "Special Educational Needs": [],
    Dyslexia: [],
    Autism: [],
    Dyspraxia: [],
    Aspergers: [],
    Dyscalculia: [],
  },
  Hobbies: {
    Sports: [],
    Archery: [],
    Athletics: [],
    Badminton: [],
    Basketball: [],
    Boxing: [],
    Canoeing: [],
    Climbing: [],
    Cricket: [],
    Cycling: [],
    Fencing: [],
    Football: [],
    Golf: [],
    Gymnastics: [],
    Hockey: [],
    "Horseback Riding": [],
    "Ice Skating": [],
    Lacrosse: [],
    "Martial Arts": [],
    Capoeira: [],
    Judo: [],
    Jujutsu: [],
    Karate: [],
    Kickboxing: [],
    "Kung Fu": [],
    "Self Defence": [],
    "Physical Education": [],
    Rugby: [],
    Sailing: [],
    Skiing: [],
    Snooker: [],
    Squash: [],
    Swimming: [],
    "Table Tennis": [],
    Tennis: [],
    Triathlon: [],
    Volleyball: [],
    Dance: [],
    Ballet: [],
    "Ballroom Dance": [],
    "Belly Dancing": [],
    "Break Dancing": [],
    "Salsa Dance": [],
    "Street Dance": [],
    Tango: [],
    "Tap Dance": [],
    Fitness: [],
    "Exercise and Fitness": [],
    "Personal Training": [],
    Pilates: [],
    Running: [],
    "Weight Lifting": [],
    Yoga: [],
    Chess: [],
    Cooking: [],
  },
};
