module.exports.constants = {
  dbCollectionNames: {
    USERS: "users",
    TUTOR_DETAIL: "tutorDetails",
    BANKING: "banking",
    WORK_EDUCTAION: "workEducation",
    SUBJECTS: "subjects",
    REVIEWS: "reviews",
    NOTIFICATION_SETTINGS: "notificationSettings",
  },
  days: {
    0: "mon",
    1: "tues",
    2: "wed",
    3: "thurs",
    4: "fri",
    5: "sat",
    6: "sun",
  },
  availability: {
    0: "unavilable",
    1: "booked",
    2: "available",
  },
  timeSlots: {
    0: "Pre 12am",
    1: "Afternoon",
    2: "Late Afternoon",
    3: "Evening",
    4: "Late Evening",
  },
  timeMapping: {
    "Pre 12am": "Pre 12am",
    Afternoon: "12 - 3pm",
    "Late Afternoon": "4 - 6pm",
    Evening: "6 - 8pm",
    "Late Evening": "After 8pm",
  },
  imageUploadTypes: {
    profilePic: 0,
    idCard: 1,
    idCardBack: 2,
    certificate: 3,
    passport: 4,
    passportBack: 5,
    driversLicense: 6,
    driversLicenseBack: 7,
    supportingDocs: 8,
  },
  applicationStatus: {
    inProgress: 0,
    submitted: 1,
    accpeted: 2,
    rejected: 3,
  },
  subjectlevels: ["Primary", "KS3", "GCSE", "IGCSE", "A-Level", "IB", "Degree"],
  modeOfTeaching: {
    online: 0,
    inperson: 1,
    both: 2,
  },
  typeOfVerificationDoc: {
    driversLicense: 0,
    passport: 1,
    idCard: 2,
  },
  lengthOfTeachingPractice: {
    lessThanAYear: 0,
    oneToFourYears: 1,
    moreThanFive: 3,
  },
};
